"""Recreate migrations

Revision ID: c9a4a7ad262d
Revises: 
Create Date: 2025-03-15 22:36:52.928621

"""
from alembic import op
import sqlalchemy as sa
from datetime import date


# revision identifiers, used by Alembic.
revision = 'c9a4a7ad262d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('satellites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('launch_date', sa.Date(), nullable=False, server_default=sa.func.current_date()))
        batch_op.add_column(sa.Column('type', sa.String(), nullable=False, server_default="Unknown"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('satellites', schema=None) as batch_op:
        batch_op.drop_column('type')
        batch_op.drop_column('launch_date')

    # ### end Alembic commands ###
