"""Adds models

Revision ID: 469861eb504e
Revises: 
Create Date: 2025-03-31 10:22:28.893973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '469861eb504e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('satellites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('orbit_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('altitude', sa.String(), nullable=False),
    sa.Column('speed', sa.String(), nullable=False),
    sa.Column('launch_date', sa.Date(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sat_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('area', sa.String(), nullable=False),
    sa.Column('climate_type', sa.String(), nullable=False),
    sa.Column('primary_focus', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['sat_id'], ['satellites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('satellite_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sat_id', sa.Integer(), nullable=False),
    sa.Column('data_type', sa.String(), nullable=False),
    sa.Column('data_value', sa.String(), nullable=False),
    sa.Column('date_recorded', sa.Date(), nullable=True),
    sa.Column('data_accuracy', sa.String(), nullable=False),
    sa.Column('measurement_unit', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('satellite_orbit', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['sat_id'], ['satellites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('satellite_data')
    op.drop_table('regions')
    op.drop_table('satellites')
    # ### end Alembic commands ###
